/*
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.survey.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.xtext.tutorial.survey.ui.internal.SurveyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SurveyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SurveyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SurveyActivator.getInstance().getInjector(SurveyActivator.ORG_ECLIPSE_XTEXT_TUTORIAL_SURVEY_SURVEY);
	}
	
}
