/*
* generated by Xtext
*/
package org.eclipse.xtext.tutorial.survey.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipse.xtext.tutorial.survey.services.SurveyGrammarAccess;

public class SurveyParser extends AbstractContentAssistParser {
	
	@Inject
	private SurveyGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipse.xtext.tutorial.survey.ui.contentassist.antlr.internal.InternalSurveyParser createParser() {
		org.eclipse.xtext.tutorial.survey.ui.contentassist.antlr.internal.InternalSurveyParser result = new org.eclipse.xtext.tutorial.survey.ui.contentassist.antlr.internal.InternalSurveyParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getQuestionAccess().getAlternatives(), "rule__Question__Alternatives");
					put(grammarAccess.getSurveyAccess().getGroup(), "rule__Survey__Group__0");
					put(grammarAccess.getPageAccess().getGroup(), "rule__Page__Group__0");
					put(grammarAccess.getFollowUpAccess().getGroup(), "rule__FollowUp__Group__0");
					put(grammarAccess.getGuardAccess().getGroup(), "rule__Guard__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getFreeTextQuestionAccess().getGroup(), "rule__FreeTextQuestion__Group__0");
					put(grammarAccess.getChoiceQuestionAccess().getGroup(), "rule__ChoiceQuestion__Group__0");
					put(grammarAccess.getChoiceAccess().getGroup(), "rule__Choice__Group__0");
					put(grammarAccess.getSurveyAccess().getNameAssignment_1(), "rule__Survey__NameAssignment_1");
					put(grammarAccess.getSurveyAccess().getTitleAssignment_2(), "rule__Survey__TitleAssignment_2");
					put(grammarAccess.getSurveyAccess().getPagesAssignment_3(), "rule__Survey__PagesAssignment_3");
					put(grammarAccess.getPageAccess().getNameAssignment_1(), "rule__Page__NameAssignment_1");
					put(grammarAccess.getPageAccess().getQuestionsAssignment_3(), "rule__Page__QuestionsAssignment_3");
					put(grammarAccess.getPageAccess().getFollowUpsAssignment_4(), "rule__Page__FollowUpsAssignment_4");
					put(grammarAccess.getFollowUpAccess().getGuardAssignment_0(), "rule__FollowUp__GuardAssignment_0");
					put(grammarAccess.getFollowUpAccess().getNextAssignment_2(), "rule__FollowUp__NextAssignment_2");
					put(grammarAccess.getGuardAccess().getQuestionAssignment_1(), "rule__Guard__QuestionAssignment_1");
					put(grammarAccess.getGuardAccess().getAnswerAssignment_3(), "rule__Guard__AnswerAssignment_3");
					put(grammarAccess.getFreeTextQuestionAccess().getNameAssignment_1(), "rule__FreeTextQuestion__NameAssignment_1");
					put(grammarAccess.getFreeTextQuestionAccess().getTextAssignment_2(), "rule__FreeTextQuestion__TextAssignment_2");
					put(grammarAccess.getChoiceQuestionAccess().getSingleAssignment_0(), "rule__ChoiceQuestion__SingleAssignment_0");
					put(grammarAccess.getChoiceQuestionAccess().getNameAssignment_2(), "rule__ChoiceQuestion__NameAssignment_2");
					put(grammarAccess.getChoiceQuestionAccess().getTextAssignment_3(), "rule__ChoiceQuestion__TextAssignment_3");
					put(grammarAccess.getChoiceQuestionAccess().getChoicesAssignment_5(), "rule__ChoiceQuestion__ChoicesAssignment_5");
					put(grammarAccess.getChoiceAccess().getFreetextAssignment_0(), "rule__Choice__FreetextAssignment_0");
					put(grammarAccess.getChoiceAccess().getNameAssignment_1(), "rule__Choice__NameAssignment_1");
					put(grammarAccess.getChoiceAccess().getTextAssignment_2(), "rule__Choice__TextAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.xtext.tutorial.survey.ui.contentassist.antlr.internal.InternalSurveyParser typedParser = (org.eclipse.xtext.tutorial.survey.ui.contentassist.antlr.internal.InternalSurveyParser) parser;
			typedParser.entryRuleSurvey();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SurveyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SurveyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
