/**
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.survey.validation;

import org.eclipse.xtext.tutorial.survey.validation.AbstractSurveyValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SurveyValidator extends AbstractSurveyValidator {
}
