/**
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.survey.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class SurveyScopeProvider extends AbstractDeclarativeScopeProvider {
}
