/*
* generated by Xtext
*/
package org.eclipse.xtext.tutorial.myquestionnaire.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyQuestionnaireAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/xtext/tutorial/myquestionnaire/parser/antlr/internal/InternalMyQuestionnaire.tokens");
	}
}
