/*
* generated by Xtext
*/
package org.eclipse.xtext.tutorial.myquestionnaire.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.tutorial.myquestionnaire.services.MyQuestionnaireGrammarAccess;

public class MyQuestionnaireParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MyQuestionnaireGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.xtext.tutorial.myquestionnaire.parser.antlr.internal.InternalMyQuestionnaireParser createParser(XtextTokenStream stream) {
		return new org.eclipse.xtext.tutorial.myquestionnaire.parser.antlr.internal.InternalMyQuestionnaireParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Questionnaire";
	}
	
	public MyQuestionnaireGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyQuestionnaireGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
