/*
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.myquestionnaire.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.xtext.tutorial.myquestionnaire.ui.internal.MyQuestionnaireActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyQuestionnaireExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MyQuestionnaireActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MyQuestionnaireActivator.getInstance().getInjector(MyQuestionnaireActivator.ORG_ECLIPSE_XTEXT_TUTORIAL_MYQUESTIONNAIRE_MYQUESTIONNAIRE);
	}
	
}
