/*
* generated by Xtext
*/
package org.eclipse.xtext.tutorial.survey;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SurveyUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.xtext.tutorial.survey.ui.internal.SurveyActivator.getInstance().getInjector("org.eclipse.xtext.tutorial.survey.Survey");
	}
	
}
