/*
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.myquestionnaire.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyQuestionnaireUiModule extends org.eclipse.xtext.tutorial.myquestionnaire.ui.AbstractMyQuestionnaireUiModule {
	public MyQuestionnaireUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
