/*
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.survey.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SurveyUiModule extends org.eclipse.xtext.tutorial.survey.ui.AbstractSurveyUiModule {
	public SurveyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
