/*
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.survey.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSurveyValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.eclipse.xtext.tutorial.survey.survey.SurveyPackage.eINSTANCE);
		return result;
	}
}
