/**
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.myquestionnaire.validation;

import org.eclipse.xtext.tutorial.myquestionnaire.validation.AbstractMyQuestionnaireValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MyQuestionnaireValidator extends AbstractMyQuestionnaireValidator {
}
