/*
* generated by Xtext
*/
package org.eclipse.xtext.tutorial.myquestionnaire;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyQuestionnaireUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.xtext.tutorial.myquestionnaire.ui.internal.MyQuestionnaireActivator.getInstance().getInjector("org.eclipse.xtext.tutorial.myquestionnaire.MyQuestionnaire");
	}
	
}
