/*
* generated by Xtext
*/
package org.eclipse.xtext.tutorial.myquestionnaire;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyQuestionnaireStandaloneSetup extends MyQuestionnaireStandaloneSetupGenerated{

	public static void doSetup() {
		new MyQuestionnaireStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

