/*
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.myquestionnaire;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyQuestionnaireRuntimeModule extends org.eclipse.xtext.tutorial.myquestionnaire.AbstractMyQuestionnaireRuntimeModule {

}
