/*
* generated by Xtext
*/
package org.eclipse.xtext.tutorial.survey;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SurveyStandaloneSetup extends SurveyStandaloneSetupGenerated{

	public static void doSetup() {
		new SurveyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

