/*
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.survey;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SurveyRuntimeModule extends org.eclipse.xtext.tutorial.survey.AbstractSurveyRuntimeModule {

}
